language: ruby
rvm:
  - "1.8.7"
  - "1.9.2"
  - "1.9.3"
  - "2.0.0"
  - "2.1.2"
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
  - jruby-head
  - ruby-head
  - rbx

script: bundle exec rspec spec

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
