language: ruby
rvm:
  - "2.0.0"
  - "2.1.2"

script: 
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres

env:
  global:
  - RAILS_ENV=test